### ISSUE TITLE
About Functional maps

### ISSUE THREAD

**Issue by cathylacus** [orlitany/DeepFunctionalMaps#7]
Dear author，
         Thanks for your work，could you give me the FM original code? Thanks!!

**Comment by orlitany** [comment]
Glad you found the work useful! Can you please elaborate on what you mean by "FM original code"?

**Comment by cathylacus** [comment]
> Glad you found the work useful! Can you please elaborate on what you mean by "FM original code"?

 I want to reproduce the results of the Functional Maps, did not find its code before, but now I had found it in the Functional Maps author's home page, thank you for your reply!
